
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/integrations/supabase/types';
import { ProductsApi } from './apis/ProductsApi';
import { DealsApi } from './apis/DealsApi';
import { OrdersApi } from './apis/OrdersApi';

const SUPABASE_URL = "https://ubqnetocrsksadsbdhlz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVicW5ldG9jcnNrc2Fkc2JkaGx6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMjYzMTUsImV4cCI6MjA2MDYwMjMxNX0.pq9DQRwVs2ycK6AnNceXEHYsqy229dM1T8I0qBc1wNE";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Base API class for common functionality
export class BaseApi {
  protected supabase = supabase;
  
  protected ensureStringId(id: string | number): string {
    return id.toString();
  }
}

// Main API class that combines all specialized APIs
export class SupabaseApi {
  public products: ProductsApi;
  public deals: DealsApi;
  public orders: OrdersApi;
  
  constructor() {
    this.products = new ProductsApi();
    this.deals = new DealsApi();
    this.orders = new OrdersApi();
  }
}

// Hook for using the Supabase API
export const useSupabaseApi = () => {
  return new SupabaseApi();
};
