
// This file is automatically generated. Do not edit it directly.
import { ProductsApi } from './apis/ProductsApi';
import { DealsApi } from './apis/DealsApi';
import { OrdersApi } from './apis/OrdersApi';
import { supabase } from '@/integrations/supabase/client';

export { supabase };
export { BaseApi } from './BaseApi';

// Main API class that combines all specialized APIs
export class SupabaseApi {
  public products: ProductsApi;
  public deals: DealsApi;
  public orders: OrdersApi;
  
  constructor() {
    this.products = new ProductsApi();
    this.deals = new DealsApi();
    this.orders = new OrdersApi();
  }
}

// Hook for using the Supabase API
export const useSupabaseApi = () => {
  return new SupabaseApi();
};
